[project]
name = "holycluster"
requires-python = ">= 3.8"
version = "0.1.0"
dependencies = [
    "websockets",
    "fastapi",
    "httpx",
    "uvicorn",
]

[project.optional-dependencies]
omnirig = ["omnipyrig"]
